name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Git Semantic Version
        id: version
        uses: PaulHatch/semantic-version@v4.0.3
        with:
          major_pattern: "major:"
          minor_pattern: "feat:|fix:"
          tag_prefix: "v"
          short_tags: true
          bump_each_commit: false
          branch: HEAD
          format: "$major.$minor.$patch"

      - name: Debug Semantic Version Outputs
        run: |
          echo "Version: ${{ steps.version.outputs.version }}"

      - name: Set Docker Version
        id: set_docker_version
        run: echo "VERSION=${{ steps.version.outputs.version }}" >> $GITHUB_ENV

      - name: Docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
      - name: Build and Push Docker Image
        env:
          MAJOR: ${{ steps.version.outputs.major }}
          MINOR: ${{ steps.version.outputs.minor }}
          PATCH: ${{ steps.version.outputs.patch }}
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t "cryss/bookhub:${MAJOR}.${MINOR}.${PATCH}" --push .
          docker buildx build --platform linux/amd64,linux/arm64 -t "cryss/bookhub:latest" --push .

